spring.application.name=hr-payroll
server.port=8101
spring.cloud.loadbalancer.enabled=true
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
spring.cloud.loadbalancer.configurations=static
spring.cloud.loadbalancer.eager-load.clients[0]=hr-worker
spring.cloud.loadbalancer.hr-worker.instances[0].host=localhost
spring.cloud.loadbalancer.hr-worker.instances[0].port=8001
spring.cloud.loadbalancer.hr-worker.instances[1].host=localhost
spring.cloud.loadbalancer.hr-worker.instances[1].port=8002
logging.level.org.springframework.cloud=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.cloud.loadbalancer.core=TRACE
logging.level.feign=TRACE